services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cloud_publishing
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot_password", "--protocol=tcp"]
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 10s

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/cloud_publishing?useUnicode=true&characterEncoding=utf8
      JWT_SECRET: 3563C7YujY767aDLvnWvMbIG6nzrlp7XrpCPtTp+Ip7rs
      JWT_ACCESS_EXPIRATION_MS: 3600000
      JWT_REFRESH_EXPIRATION_MS: 604800000
    healthcheck:
      test: [ "CMD", "bash", "-c", "</dev/null > /dev/tcp/localhost/8080" ]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 10s

  itest:
    build:
      context: ..
      dockerfile: itest/Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    environment:
      BACKEND_URL: http://backend:8080
      DB_URL: jdbc:mysql://mysql:3306/cloud_publishing?useUnicode=true&characterEncoding=utf8
      DB_USER: user
      DB_PASSWORD: pass

volumes:
  mysql_data: